### ISSUE TITLE
Authenticated channels

### ISSUE THREAD

**Issue by bkeepers** [probot/smee-client#27] opened 2017-12-20 15:29 UTC
Even though channel names are random, it seems a little sketchy to broadcast events to any client that can guess a URL. It'd be great to have authenticated channels that prevent random clients from eavesdropping.

Here are a couple options for how it could work:

1. Pass the webhook secret in the `Authorization` header when the client connects. Before webhooks are delivered to a client, use the secret provided by the client to [verify the signature](https://github.com/octokit/webhooks.js/tree/master/verify). If it doesn't validate, avoid delivering the event (and maybe even reject the client with a 401).

1. Add OAuth to smee.io and generate a secret for each user. The user can create channels as `smee.io/:username/anything-you-want`, but any channel starting with `/:username/` must include the user's token in the `Authorization` header.

Either way, the client would have to pass a secret, it's just a question of whether that is the webhook secret configured on GitHub, or a secret from smee.io

```
new EventSource("https://smee.io/my-channel-name", {
  headers: {"Authorization": "my-secret"}
});
```

cc https://github.com/bkeepers/webhook-proxy/issues/3

**Comment by tcbyrd** [comment] 2017-12-20 15:43
> Add OAuth to smee.io and generate a secret for each user.

I like this option because it also means we can more securely persist payloads from private repos. Right now, if you guessed a channel name and somebody was testing a private repo, you'd see all that data in the clear. I feel like we can't add persistent channels until we have a way to protect them somehow. OAuth solves that.

**Comment by knrt10** [comment] 2018-03-24 18:32
@bkeepers I also like this option. Can i work on this issue?

**Comment by knrt10** [comment] 2018-03-25 08:29
@tcbyrd @bkeepers I am working on this issue but on running locally when I am trying to make changes in `serve/components/Blank.js` or any other file in `src/components` folder it is not reflecting in my localhost. I was adding OAuth but not able to proceed due to this error. Please help?

Thanks is advance.

**Comment by knrt10** [comment] 2018-03-25 20:58
@bkeepers @JasonEtco @tcbyrd Please review my PR.
Thanks in advance.

**Comment by knrt10** [comment] 2018-03-26 10:29
What I get from this is that: 
1.) Whenever a person makes a post request to `:/channel` then along with that we should set `Authorization` header and send some secret along with them.
2.) On making a get request we should check that secret with user's secret and then deliver them payload.

Am I right?
**cc** @bkeepers  @tcbyrd

**Comment by knrt10** [comment] 2018-03-26 13:03
How to get client's secret in server side to code? I want to pass it in authorization header. Please help.

**Comment by tcbyrd** [comment] 2018-03-26 21:39
@knrt10 The general way that's handled is to use query parameters in the URL, then have the server parse that. An example that may help is in [probot/invite](https://github.com/probot/invite/blob/master/lib/oauth.js): 

https://github.com/probot/invite/blob/07f0e1a9a17253801def6d1a9dba20865b9591db/lib/oauth.js#L7-L19

Thanks for working on a PR for this! I'll try and find some time this week to review any contributions.

**Comment by knrt10** [comment] 2018-03-27 01:22
@tcbyrd Thanks will look into that and try implementing it.

**Comment by knrt10** [comment] 2018-03-27 02:22
@tcbyrd I tried to implement this part but faced with 2 problems
Here is my code
```
const params = querystring.stringify({
      clientsecret: process.env.WEBHOOK_PROXY_URL
    })
    res.redirect(307, `${protocol}://${host}/${channel}?${params}`)
```

I am sending clientsecret in the header of URL.

**Problem I am facing is** :
For testing how to get this secret in header?

When there is get request in `/:channel`

I tried this code

```
app.get('/:channel', (req, res, next) => {
    if (req.accepts('html')) {
      const URLsecret = req.query.clientsecret
      const clientsecret = querystring.parse({
        clientsecret: process.env.WEBHOOK_PROXY_URL
      })
      if(URLsecret === '' || URLsecret === null || URLsecret === undefined) {
        res.sendStatus(401)
        return next()
      }else if (clientsecret === URLsecret) {
        res.sendFile(path.join(pubFolder, 'webhooks.html'))
      }
```

**Again the problem is** in getting secret from URL. I am manually inputing in header and getting **URLsecret** but for testing how would I get **clientsecret**

**Comment by knrt10** [comment] 2018-03-27 17:34
@tcbyrd I got the above part but what I am asking is that how would I get secret from client's `.env` file? Then send it to server so that further authentication can be done.

1 way is that I write code in `smee/client` to get value from `.env` and then send it to URL. Is my approach correct. 
Please suggest if you have any other thought in mind.

**Comment by knrt10** [comment] 2018-03-27 20:41
@tcbyrd I applied some changes would you want me to open a PR?

**Comment by knrt10** [comment] 2018-03-30 16:57
@bkeepers @tcbyrd . I added github authentication when one creates a new channel. Please review changes. Thanks in advance.

**Comment by knrt10** [comment] 2018-03-30 21:21
Please review these additional features.

**Added Functionality**

To avoid eavesdropping of payloads `smee.io` will require `Github's` authentication.

1) User will only need once to login with their Github account and authorize the app.
2) User can create as many channels they want to which they have only access to.
3) User cannot access channels until and unless they are logged from Github.

**Preview**

This is showing user logging in.

<img src="http://res.cloudinary.com/dsyvg5xwi/image/upload/v1522443412/1_cb4qgq.gif"/>


This shows if another User try to access channel of other user they cannot see it and for now just returning simple error.

<img src="http://res.cloudinary.com/dsyvg5xwi/image/upload/v1522443415/2_nfn7tq.gif"/>

**Comment by knrt10** [comment] 2018-05-30 02:58
Yes still relevant

**Comment by knrt10** [comment] 2018-08-28 03:37
@tcbyrd will you please review my PR

**Comment by knrt10** [comment] 2018-11-26 07:52
Yes Pr is there

**Comment by dhirschfeld** [comment] 2022-11-30 03:44
Are there any plans to add this functionality? Unfortunately, I won't be able to make use of this service without it :(

**Comment by tcbyrd** [comment] 2022-12-01 01:38
Authentication is not likely going to be added to smee.io. Another team is working on a native integration using the `gh` command line, which will likely be the best way forward for people who need this feature: https://github.blog/changelog/2022-11-16-webhook-forwarding-in-the-github-cli-public-beta/

Once that feature is out of beta, we may end up shutting down smee.io entirely since it's effectively the same functionality with a better integration.

cc @gr2m in case you have any other thoughts, but I'm going to close this issue for now.

**Closed by tcbyrd** 2022-12-01 01:38 UTC
Labels: pinned
